version: "3"

services:
  status:
    image: trieve/public-status-page
    build: .
    restart: always
    ports:
      - 3003:3000
    environment:
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - PORT=3003
      - KUBECONFIG=${KUBECONFIG:-/root/.kube/config}
    network_mode: "host"
    volumes:
      - ~/.kube:/root/.kube:ro

networks:
  app-network:
    driver: bridge
